apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  selector:
    matchLabels:
     app: users
  replicas: 2
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: users:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
